services:
  # Nestjs back API is not used
  # back:
  #   container_name: "back"
  #   build: 
  #     context: "./src-back"
  #     dockerfile: "../dockerfiles/Dockerfile.back.dev"
  #   ports:
  #     - 9000:9000
  #     - 9229:9229
  #   tty: true
  #   volumes:
  #     - ./src-back:/app
  #     - /app/node_modules
  #   environment:
  #     - NODE_ENV=development
  #   depends_on:
  #     - db

  back:
    container_name: "back"
    build: 
      context: "./back-fastapi"
      dockerfile: "../dockerfiles/Dockerfile.back-fastapi.dev"
    ports:
      - 8000:8000
      - 5678:5678
    tty: true
    volumes:
      - ./back-fastapi:/app
    restart: always
    # command: ["sh", "-c", "python -m debugpy --wait-for-client --listen 0.0.0.0:5678 -m uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"]
    environment:
      - DEBUG=True
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  front:
    container_name: "front"
    build: 
      context: "./src-front"
      dockerfile: "../dockerfiles/Dockerfile.front.dev"
    ports:
      - 5173:5173
    tty: true
    volumes:
      - ./src-front:/app
      - /app/node_modules
    # environment:
      # REACT_APP_API_URL: ${REACT_APP_API_URL}
    depends_on:
      - back
  
  db:
    image: postgres:15.3-bullseye
    container_name: Postgres
    restart: always
    environment:
      # POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: budgeter
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: Adminer
    restart: always
    ports:
      - 8080:8080