services:
  api-orgfin:
    container_name: "api-orgfin"
    platform: "linux/amd64"
    build:
      context: "./back-fastapi"
      dockerfile: "./Dockerfile"
      target: ${TARGET:-dev}
    env_file:
      - ${APP_ENV_FILE:-./back-fastapi/.env}
    ports:
      - 8000:8000
      - 5678:5678
    environment:
      - DB_HOST=db-orgfin
    tty: true
    volumes:
      - ./back-fastapi:/app
    restart: always
    depends_on:
      - db-orgfin

  front-orgfin:
    container_name: "front-orgfin"
    build:
      context: "./src-front"
      dockerfile: "../docker/Dockerfile.front.dev"
    ports:
      - 5173:5173
    tty: true
    volumes:
      - ./src-front:/app
      - /app/node_modules

  db-orgfin:
    image: postgres:15.3-bullseye
    container_name: Postgres-orgfin
    restart: always
    environment:
      # POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: budgeter
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  adminer-orgfin:
    image: adminer
    container_name: Adminer-orgfin
    restart: always
    ports:
      - 8080:8080

  redis-orgfin:
    image: redis:alpine
    container_name: redis-orgfin
    command: redis-server --bind 0.0.0.0
    ports:
      - 6379:6379
    restart: always

  celery-orgfin:
    container_name: "celery-orgfin"
    platform: "linux/amd64"
    build:
      context: "./back-fastapi"
      dockerfile: "./Dockerfile"
      target: ${TARGET:-dev}
    env_file:
      - ${APP_ENV_FILE:-./back-fastapi/.env}
    command: celery -A app.celery worker -l info
    volumes:
      - ./back-fastapi:/app
    depends_on:
      - redis-orgfin

  celery-beat-orgfin:
    container_name: "celery-beat-orgfin"
    platform: "linux/amd64"
    env_file:
      - ${APP_ENV_FILE:-./back-fastapi/.env}
    build:
      context: "./back-fastapi"
      dockerfile: "./Dockerfile"
      target: ${TARGET:-dev}
    command: celery -A app.celery beat -l info
    volumes:
      - ./back-fastapi:/app
    depends_on:
      - redis-orgfin

  dashboard-redis-celery:
    container_name: "dashboard-redis-celery"
    build:
      context: "./back-fastapi"
      dockerfile: "./Dockerfile"
      target: ${TARGET:-dev}
    env_file:
      - ${APP_ENV_FILE:-./back-fastapi/.env}
    command: celery --broker=$$CELERY_BROKER_URL/0 flower --port=5555
    ports:
      - 5556:5555
    depends_on:
      - api-orgfin
      - redis-orgfin
      - celery-orgfin
      - celery-beat-orgfin

