services:
  back:
    container_name: "back"
    build: 
      context: "./src-back"
      dockerfile: "../dockerfiles/Dockerfile.back.dev"
    ports:
      - 9000:9000
      - 9229:9229
    tty: true
    volumes:
      - ./src-back:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - db

  # front:
  #   container_name: "front"
  #   build: 
  #     context: "./src-front"
  #     dockerfile: "../dockerfiles/Dockerfile.front.dev"
  #   ports:
  #     - 3000:3000
  #   tty: true
  #   volumes:
  #     - ./src-front:/app
  #     - /app/node_modules
  #   environment:
  #     REACT_APP_API_URL: ${REACT_APP_API_URL}
  #   depends_on:
  #     - back
  
  db:
    image: postgres:15.3-bullseye
    container_name: Postgres
    restart: always
    environment:
      # POSTGRES_USER: urlshortener
      POSTGRES_PASSWORD: budgeter
    ports:
      - 5432:5432
    volumes:
      - ./dbdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: Adminer
    restart: always
    ports:
      - 8080:8080