- op: replace
  path: /spec/template/spec/containers/0/command
  value:
    - gunicorn
    - app.main:app
    - -k
    - uvicorn.workers.UvicornWorker
    - --bind
    - 0.0.0.0:8000
    - --access-logfile
    - "-"