[project]
name = "back-fastapi"
version = "1.5.17"
requires-python = ">=3.12"
dependencies = [
    "aiofiles>=24.1.0",
    "aiosmtplib>=3.0.2",
    "alembic>=1.15.2",
    "amqp>=5.3.1",
    "annotated-types>=0.7.0",
    "anyio>=4.9.0",
    "appnope>=0.1.4",
    "astroid>=3.3.9",
    "asttokens>=3.0.0",
    "backcall>=0.2.0",
    "bcrypt>=4.3.0",
    "billiard>=4.2.1",
    "blinker>=1.9.0",
    "cachetools>=5.5.2",
    "celery>=5.5.1",
    "certifi>=2025.1.31",
    "cffi>=1.17.1",
    "charset-normalizer>=3.4.1",
    "click>=8.1.8",
    "click-didyoumean>=0.3.1",
    "click-plugins>=1.1.1",
    "click-repl>=0.3.0",
    "colorama>=0.4.6",
    "contourpy>=1.3.1",
    "coverage>=7.5.4",
    "cycler>=0.12.1",
    "debugpy>=1.8.2",
    "decorator>=5.1.1",
    "dill>=0.3.8",
    "dnspython>=2.6.1",
    "docutils>=0.21.2",
    "email-validator>=2.2.0",
    "executing>=2.0.1",
    "fastapi>=0.115.12",
    "fastapi-cli>=0.0.4",
    "fastapi-mail>=1.4.1",
    "flower>=2.0.1",
    "fonttools>=4.53.1",
    "gunicorn>=23.0.0",
    "h11>=0.14.0",
    "httpcore>=1.0.5",
    "httptools>=0.6.1",
    "httpx>=0.27.0",
    "humanize>=4.10.0",
    "icecream>=2.1.3",
    "idna>=3.7",
    "importlib-metadata>=8.2.0",
    "iniconfig>=2.0.0",
    "isort>=5.13.2",
    "jaraco-classes>=3.4.0",
    "jaraco-context>=5.3.0",
    "jaraco-functools>=4.0.1",
    "jedi>=0.19.1",
    "jinja2>=3.1.4",
    "keyring>=25.2.1",
    "kiwisolver>=1.4.5",
    "kombu>=5.3.7",
    "loguru>=0.7.2",
    "mako>=1.3.5",
    "markdown-it-py>=3.0.0",
    "markupsafe>=2.1.5",
    "matplotlib>=3.10.0",
    "mccabe>=0.7.0",
    "mdurl>=0.1.2",
    "more-itertools>=10.3.0",
    "mypy>=1.10.1",
    "mypy-extensions>=1.0.0",
    "nh3>=0.2.18",
    "numpy>=1.26.4",
    "orjson>=3.10.6",
    "packaging>=24.1",
    "parso>=0.8.4",
    "pendulum>=3.0.0",
    "pillow>=10.4.0",
    "pip-review>=1.3.0",
    "pkginfo>=1.10.0",
    "platformdirs>=4.2.2",
    "pluggy>=1.5.0",
    "prometheus-client>=0.20.0",
    "prompt-toolkit>=3.0.47",
    "pyarrow>=18.0.0",
    "pydantic>=2.8.2",
    "pydantic-settings>=2.3.4",
    "pydantic-core>=2.20.1",
    "pydevd-pycharm>=241.18034.82",
    "pygments>=2.18.0",
    "pyjwt>=2.8.0",
    "pylint>=3.2.5",
    "pyloco>=0.0.139",
    "pyparsing>=3.1.2",
    "pytest>=8.2.2",
    "pytest-cov>=5.0.0",
    "python-dateutil>=2.9.0.post0",
    "python-dotenv>=1.0.1",
    "python-multipart>=0.0.9",
    "pytz>=2024.1",
    "pyyaml>=6.0.1",
    "readme-renderer>=44.0",
    "redis>=5.0.7",
    "requests>=2.32.3",
    "requests-toolbelt>=1.0.0",
    "rfc3986>=2.0.0",
    "rich>=13.7.1",
    "setuptools>=70.2.0",
    "shellingham>=1.5.4",
    "simplewebsocketserver>=0.1.2",
    "six>=1.16.0",
    "sniffio>=1.3.1",
    "sqlalchemy>=2.0.31",
    "starlette>=0.40.0",
    "time-machine>=2.14.2",
    "tomlkit>=0.12.5",
    "tornado>=6.4.1",
    "twine>=5.1.1",
    "typer>=0.12.3",
    "types-cachetools>=5.4.0.20240717",
    "types-requests>=2.32.0.20240622",
    "typing>=3.7.4.3",
    "typing-extensions>=4.12.2",
    "tzdata>=2024.1",
    "ujson>=5.10.0",
    "urllib3>=2.2.2",
    "ushlex>=0.99.1",
    "uvicorn>=0.30.1",
    "uvloop>=0.19.0",
    "vine>=5.1.0",
    "watchfiles>=0.22.0",
    "wcwidth>=0.2.13",
    "websocket-client>=1.8.0",
    "websockets>=12.0",
    "zipp>=3.19.2",
    "psycopg2>=2.9.10",
    "google-auth>=2.37.0",
    "pyasn1>=0.6.1",
    "pyasn1-modules>=0.4.1",
]
